### PR TITLE
JFrog V2 Service Connections

### PR DESCRIPTION
**Pull request by davidcorrigan714**
## All Submissions:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] I have updated the documentation accordingly.
* [x] I have added tests to cover my changes.
* [x] All new and existing tests passed.
* [ ] My code follows the code style of this project.
* [ ] I ran lint checks locally prior to submission.
* [x] Have you checked to ensure there aren't other open PRs for the same update/change?

## What about the current behavior has changed?

Adding the JFrog V2 service connections. I just copy+pasted the existing Artifactory resource, tests & docs then adjusted accordingly. They all use the same parameters. One unit test needed fixing, the argocd connection seemed to be based on these so I adopted the same fix that was in that resource.

Unit & acceptance tests for the service connections have passed. Docs have been updated.

The formatting scripts in the repo want to reformat all sorts of stuff. I'll leave that to Microsoft's discretion when I upstream this.

### CODE REVIEW

**Comment by davidcorrigan714** [comment]
[Here](https://developer.hashicorp.com/terraform/plugin/sdkv2/schemas) are the docs for creating resources in providers which will be the most relevant details for reviewing this PR.

**Review by irwand — APPROVED** [review]
I diff the new file against existing file and confirmed that it's mostly copying + replacing class/variable names.
When submitting this to MS, ask if they rather name all these V2 or just remove the old ones.. though that might be a compatibility breakage.

**Comment by davidcorrigan714** [comment]
I'm debugging an issue where credentials aren't being set properly when changed - like the first time it works, but then an update to the api token breaks it.

**Comment by davidcorrigan714** [comment]
There is an issue storing secrets that's been [reported upstream](https://github.com/microsoft/terraform-provider-azuredevops/issues/692). I'll address it in another PR for our fork of the provider.

**Pull request merged**
